homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret my_latitude
  longitude: !secret my_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 196
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London
  #Domain customize
  customize_domain:
    script:
      hidden: true
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:
#  javascript_version: latest

# Enables configuration UI
config:

#Error log
logger:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

#Emulated Hue Bridge
emulated_hue:
  host_ip: 192.168.1.81
  expose_by_default: false
  off_maps_to_on_domains:
    - script
#  exposed_domains:
#    - switch
#    - script
#    - light

# Track the sun
sun:

# IKEA Tradfri gateway
tradfri:
  host: 192.168.1.97
  allow_tradfri_groups: false

# Nest Thermostat
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

sensor:
# Weather prediction
  - platform: yr
# Show Time
  - platform: time_date
    display_options:
      - 'time'

#media players
media_player:
  - platform: plex
  
# Text to speech
tts:
  - platform: google

light:
#MQTT Kitchen LED strip
  - platform: mqtt_json
    command_topic: "RGB/0035F793/json/set"
    name: 'Kitchen strip light'
    brightness: true
    effect: true
    rgb: true
    state_topic: "RGB/0035F793/json/state"
#Kitchen Spotlights SONOFF Switch
  - platform: mqtt
    command_topic: "cmnd/sonoff/power"
    name: 'kitchen lights'
    state_topic: "stat/sonoff/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

#CEC Control
hdmi_cec:
  devices:
    TV: 0.0.0.0
    Fire TV: 2.0.0.0
    Chromecast: 3.0.0.0
    Pi: 1.0.0.0

# MQTT Server
mqtt:
  discovery: true
  discovery_prefix: homeassistant
  broker: 192.168.1.81
  port: 1883
  username: !secret mqtt_username
  password: !secret mqtt_password

#Input Boolean section
input_boolean:
  alexa_lights_toggle:
    name: 'Alexa Lights Toggle'
    initial: 'off'
  lights_shutdown_sequence:
    name: 'Lights shutdown sequence'
    initial: 'off'
  dummy_boolean:
    name: 'Dummy boolean'
    initial: 'off'
  lights_on_override:
    name: 'Override lights on automations'
    initial: 'off'
  alexa_toggle_call:
    name: 'Alexa called lights'
    initial: 'off'

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
# scene: !include scenes.yaml
# secrets: !include secrets.yaml built in to HA, no need to define